pojisteniapp/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

urlpatterns = [
path('o-aplikaci/', views.index, name= 'o-aplikaci'),
path('', RedirectView.as_view(url= 'o-aplikaci/')),
path('pojistenci/', views.PojistnecListView.as_view(), name= 'pojistenci'),
path('typy-pojisteni/', views.TypPojisteniListView.as_view(), name= 'typy-pojisteni'),
path('pojisteni_list/', views.PojisteniListView.as_view(), name= 'pojisteni_list'),
path('pojistenec/<int:pk>', views.PojistenecDetailView.as_view(), name= 'pojistenec'),
path('pojisteni_detail/<uuid:pk>', views.PojisteniDetailView.as_view(), name= 'pojisteni_detail'),
path('pojistenec/create/', views.PojistenecCreate.as_view(), name='pojistenec_create'),
path('pojistenec/<int:pk>/update/', views.PojistenecUpdate.as_view(), name='pojistenec_update'),
path('pojistenec/<int:pk>/delete/', views.PojistenecDelete.as_view(), name='pojistenec_delete'),
path('pojisteni/create/', views.vytvorit_pojisteni, name='pojisteni_create'),
path('pojisteni/<uuid:pk>/update/', views.upravit_pojisteni, name='pojisteni_update'),
path('pojisteni/<uuid:pk>/delete/', views.PojisteniDelete.as_view(), name='pojisteni_delete'),
path('typ-pojisteni/create/', views.TypPojisteniCreate.as_view(), name='typ-pojisteni_create'),
path('typ-pojisteni/<int:pk>/delete/', views.TypPojisteniDelete.as_view(), name='typ-pojisteni_delete'),
path('pojistenec/<int:pk>/pojistit-pojistence/', views.pojistit_pojistence, name='pojistit-pojistence')
]

pojisteniproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path('pojisteniapp/', include('pojisteniapp.urls')),
    path('', RedirectView.as_view(url='pojisteniapp/')),
]

# Use static() to add URL mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pojisteniapp/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MinValueValidator, MaxValueValidator
import uuid
from django.urls import reverse

# Create your models here.

class Pojistenec(models.Model):

    jmeno = models.CharField('Jméno', max_length=30)
    prijmeni = models.CharField('Příjmení', max_length=30)
    email = models.EmailField(max_length=254)
    telefon = PhoneNumberField()
    ulice = models.CharField(max_length=30)
    cislo_popisne = models.IntegerField('Číslo popisné')
    mesto = models.CharField('Město', max_length=30)
    psc = models.IntegerField('PSČ', validators=[MinValueValidator(10000), MaxValueValidator(99999)])

    def __str__(self) -> str:
        return f'{self.jmeno} {self.prijmeni}'
    
    def get_absolute_url(self):
        return reverse("pojistenec", kwargs={"pk": self.pk})
    

    class Meta:
        ordering = ['prijmeni', 'jmeno', 'mesto']

class TypPojisteni(models.Model):

    jmeno = models.CharField('Typ pojištění', max_length=30)

    def __str__(self) -> str:
        return f'{self.jmeno}'
    
    class Meta:
        ordering = ['jmeno']

class Pojisteni(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unikátní ID pojištění')
    typ_pojisteni = models.ForeignKey(TypPojisteni, on_delete=models.RESTRICT, verbose_name='Typ pojištění')
    pojistenec = models.ForeignKey(Pojistenec, on_delete=models.CASCADE, verbose_name='Pojištěnec')
    castka = models.IntegerField('Částka')
    mesicni_pojistne = models.IntegerField('Měsíční pojistné')
    platnost_od = models.DateField()
    platnost_do = models.DateField()

    predmet_pojisteni = models.CharField('Předmět pojištění', max_length=30, blank=True, null=True, help_text='Vyplňte pouze v případě, že předmět pojištění není patrný (např. u pojištění majetku).')

    def __str__(self) -> str:
        return f'{self.typ_pojisteni.jmeno} pojištěnce {self.pojistenec.jmeno} {self.pojistenec.prijmeni}'
    
    def get_absolute_url(self):
        return reverse("pojisteni_detail", args=[self.id])

    class Meta:
        ordering = ['pojistenec__prijmeni', 'pojistenec__jmeno', 'pojistenec__mesto' ,'typ_pojisteni__jmeno']

pojisteniapp/forms.py
from django.forms import ModelForm
from django import forms
from .models import Pojisteni

class PojistitPojistenceForm(ModelForm):
    class Meta:
        model = Pojisteni
        fields = ['typ_pojisteni', 'castka', 'mesicni_pojistne', 'platnost_od', 'platnost_do', 'predmet_pojisteni']
        widgets = {
            'platnost_od' : forms.SelectDateWidget,
            'platnost_do' : forms.SelectDateWidget,
        }

class VytvoritPojisteniForm(ModelForm):
    class Meta:
        model = Pojisteni
        fields = ['typ_pojisteni', 'pojistenec' , 'castka', 'mesicni_pojistne', 'platnost_od', 'platnost_do', 'predmet_pojisteni']
        widgets = {
            'platnost_od' : forms.SelectDateWidget,
            'platnost_do' : forms.SelectDateWidget,
        }

pojisteniapp/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Pojistenec, TypPojisteni, Pojisteni

from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect

# Create your views here.

def index(request):
    """View function for home page of site."""
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html')

class PojistnecListView(generic.ListView):
    model = Pojistenec
    paginate_by = 6

class PojisteniListView(generic.ListView):
    model = Pojisteni
    paginate_by = 6

class TypPojisteniListView(generic.ListView):
    model = TypPojisteni
    paginate_by = 6
    template_name = 'pojisteniapp/typ-pojisteni_list.html'

class PojistenecDetailView(generic.DetailView):
    model = Pojistenec

class PojisteniDetailView(generic.DetailView):
    model = Pojisteni

class PojistenecCreate(CreateView):
    model = Pojistenec
    fields = ['jmeno', 'prijmeni', 'email', 'telefon', 'ulice', 'cislo_popisne', 'mesto', 'psc']

class PojistenecUpdate(UpdateView):
    model = Pojistenec
    fields = ['jmeno', 'prijmeni', 'email', 'telefon', 'ulice', 'cislo_popisne', 'mesto', 'psc']

class PojistenecDelete(DeleteView):
    model = Pojistenec
    success_url = reverse_lazy('pojistenci')

class PojisteniCreate(CreateView):
    model = Pojisteni
    fields = ['typ_pojisteni', 'pojistenec', 'castka', 'mesicni_pojistne', 'platnost_od', 'platnost_do', 'predmet_pojisteni']

class PojisteniUpdate(UpdateView):
    model = Pojisteni
    fields = ['typ_pojisteni', 'pojistenec', 'castka', 'mesicni_pojistne', 'platnost_od', 'platnost_do', 'predmet_pojisteni']

class PojisteniDelete(DeleteView):
    model = Pojisteni
    success_url = reverse_lazy('pojisteni')

class TypPojisteniCreate(CreateView):
    model = TypPojisteni
    fields = ['jmeno']
    success_url = reverse_lazy('typy-pojisteni')
    template_name = 'pojisteniapp/typ-pojisteni_form.html'

class TypPojisteniDelete(DeleteView):
    model = TypPojisteni
    success_url = reverse_lazy('typy-pojisteni')
    template_name = 'pojisteniapp/typ-pojisteni_confirm_delete.html'


from .forms import PojistitPojistenceForm, VytvoritPojisteniForm

def pojistit_pojistence(request, pk):
    pojistenec = get_object_or_404(Pojistenec, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = PojistitPojistenceForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():


            pojisteni = Pojisteni(typ_pojisteni= form.cleaned_data['typ_pojisteni'],
                                  pojistenec = pojistenec,
                                  castka = form.cleaned_data['castka'],
                                  mesicni_pojistne = form.cleaned_data['mesicni_pojistne'],
                                  platnost_od = form.cleaned_data['platnost_od'],
                                  platnost_do = form.cleaned_data['platnost_do'],
                                  predmet_pojisteni = form.cleaned_data['predmet_pojisteni'],
                                  )
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            pojisteni.save()

            # redirect to a new URL:
            return HttpResponseRedirect(pojistenec.get_absolute_url())

    # If this is a GET (or any other method) create the default form.
    else:
        form = PojistitPojistenceForm(initial={'pojistenec': pojistenec.pk})

    context = {
        'form': form,
        'pojistenec': pojistenec
    }

    return render(request, 'pojisteniapp/pojisteni-pojistence_form.html', context)


from django.urls import reverse

def vytvorit_pojisteni(request):
    import uuid
    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = VytvoritPojisteniForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():

            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            form.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('pojisteni_list'))

    # If this is a GET (or any other method) create the default form.
    else:
        form = VytvoritPojisteniForm()

    context = {
        'form': form,
    }

    return render(request, 'pojisteniapp/pojisteni_form.html', context)

def upravit_pojisteni(request, pk):
    pojisteni = get_object_or_404(Pojisteni, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = VytvoritPojisteniForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():

            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            pojisteni.typ_pojisteni= form.cleaned_data['typ_pojisteni']
            pojisteni.pojistenec = form.cleaned_data['pojistenec']
            pojisteni.castka = form.cleaned_data['castka']
            pojisteni.mesicni_pojistne = form.cleaned_data['mesicni_pojistne']
            pojisteni.platnost_od = form.cleaned_data['platnost_od']
            pojisteni.platnost_do = form.cleaned_data['platnost_do']
            pojisteni.predmet_pojisteni = form.cleaned_data['predmet_pojisteni']
            pojisteni.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('pojisteni_list'))

    # If this is a GET (or any other method) create the default form.
    else:
        form = VytvoritPojisteniForm(initial={
            'typ_pojisteni':pojisteni.typ_pojisteni,
            'pojistenec':pojisteni.pojistenec,
            'castka':pojisteni.castka,
            'mesicni_pojistne':pojisteni.mesicni_pojistne,
            'platnost_od': pojisteni.platnost_od,
            'platnost_do': pojisteni.platnost_do,
            'predmet_pojisteni': pojisteni.predmet_pojisteni,
        })

    context = {
        'form': form,
    }

    return render(request, 'pojisteniapp/pojisteni_form.html', context)

pojisteniapp/templates/pojisteniapp/pojistenec_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h2>Vymazat pojištěnce</h2>

<p>Jste si jistí, že chcete vymazat pojištěnce <strong>{{ pojistenec }}</strong>?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Ano, vymazat." />
</form>

{% endblock %}

pojisteniapp/templates/pojisteniapp/pojistenec_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>Pojištěnec: {{ pojistenec.jmeno }} {{pojistenec.prijmeni}}</h2>

  <p><strong>Jméno:</strong> {{pojistenec.jmeno}}</p>
  <p><strong>Příjmení:</strong> {{pojistenec.prijmeni}}</p>
  <p><strong>Email:</strong> {{pojistenec.email}}</p>
  <p><strong>Telefon:</strong> {{pojistenec.telefon}}</p>
  <p><strong>Ulice a č.p.:</strong> {{pojistenec.cislo_popisne}}</p>
  <p><strong>Město:</strong> {{pojistenec.mesto}}</p>
  <p><strong>PSČ:</strong>{{pojistenec.psc}}</p>

  <div>
    <a class = 'button modifier' href="{% url 'pojistenec_update' pojistenec.id%}"> Upravit </a>
    <a class = 'button constructor' href="{% url 'pojistit-pojistence' pojistenec.id%}"> Pojistit </a>
    <a class = 'button destructor' href="{% url 'pojistenec_delete' pojistenec.id%}"> Vymazat </a>
  </div>


  {% if pojistenec.pojisteni_set.all %}
  <div>
    <h3>Sjednaná pojištění</h3>
    <table>
      <thead>
        <th>Typ pojištění</th>
        <th>Částka</th>
        <th>Měsíční pojistné</th>
        <th>Platnost od</th>
        <th>Platnost do</th>
        <th>ID pojištění</th>
        <th>Možné úpravy</th>
      </thead>  
      {% for pojisteni in pojistenec.pojisteni_set.all %}
      <tr>
        <td>
          {{pojisteni.typ_pojisteni}}
        </td>
        <td>
          {{pojisteni.castka}} Kč
        </td>
        <td>
          {{pojisteni.mesicni_pojistne}} Kč
        </td>
        <td>
          {{pojisteni.platnost_od}}
        </td>
        <td>
          {{pojisteni.platnost_do}}
        </td>
        <td>
          <a href="{{pojisteni.get_absolute_url}}">{{pojisteni.id}}</a>
        </td>
        <td>
          úpravy
        </td>
      </tr>
    {% endfor %}
    </table>
  </div>
  {% else %}
    <h3>Pojištěnec nemá registrovaná žádná pojištění</h3>
  {% endif %}
{% endblock %}

pojisteniapp/templates/pojisteniapp/pojistenec_form.html
{% extends "base_generic.html" %}

{% block content %}
{% if request.resolver_match.url_name == 'pojistenec_create' %}
<h2>Registrovat nového pojištěnce</h2>
{% elif request.resolver_match.url_name == 'pojistenec_update'%}
<h2>Upravit údaje pojištěnce</h2>
{%endif%}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Uložit" />
  </form>
{% endblock %}

pojisteniapp/templates/pojisteniapp/pojistenec_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 class= 'list-header'>Seznam pojištěnců</h1>
  {% if pojistenec_list %}
  <table class= 'list-table'>
    <thead>
      <th>Jméno</th>
      <th>Bydliště</th>
      <th>Telefon</th>
      <th>Email</th>
      <th>Možné úpravy</th>
    </thead>
    {% for pojistenec in pojistenec_list %}
    <tr>
      <td class= 'td-jmeno-pojistence'>
        <a href="{{ pojistenec.get_absolute_url }}">{{ pojistenec.jmeno }} {{pojistenec.prijmeni}}</a>
      </td>
      <td>
        {{pojistenec.ulice}} {{pojistenec.cislo_popisne}}, {{pojistenec.mesto}}
      </td>
      <td>
        {{pojistenec.telefon}}
      </td>
      <td>
        {{pojistenec.email}}
      </td>
      <td>
        <a class = 'button modifier' href="{% url 'pojistenec_update' pojistenec.id%}"> Upravit</a> <a class = 'button constructor' href="{% url 'pojistit-pojistence' pojistenec.id %}"> Pojistit</a> <a class = 'button destructor' href="{% url 'pojistenec_delete' pojistenec.id%}"> Vymazat</a>
      </td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
    <p>Zatím nejsou zaregistrováni žádní pojištěnci.</p>
  {% endif %}

{% endblock %}

{% block register_entity%}
<div class= 'outside-list-button-container'>
<a class = 'button constructor' href="{% url 'pojistenec_create'%}"> Registrovat pojištěnce </a>
</div>
{% endblock %}

pojisteniapp/templates/pojisteniapp/pojisteni-pojistence_form.html
{% extends "base_generic.html" %}

{% block content %}
<h2>Pojistit pojištěnce {{pojistenec}}</h2>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Uložit" />
  </form>
{% endblock %}

pojisteniapp/templates/pojisteniapp/pojisteni_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h2>Vymazat pojištění</h2>

<p>Jste si jistí, že chcete vymazat pojištění <strong>{{pojisteni.typ_pojisteni}}</strong> pojištěnce <strong>{{ pojisteni.pojistenec }}</strong> (id: {{pojisteni.id}})?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Ano, vymazat." />
</form>

{% endblock %}

pojisteniapp/templates/pojisteniapp/pojisteni_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>{{pojisteni}}</h2>

  <p><strong>Pojištěnec:</strong> <a href="{{pojisteni.pojistenec.get_absolute_url}}">{{pojisteni.pojistenec.jmeno}} {{pojisteni.pojistenec.prijmeni}}</a></p>
  <p><strong>Typ pojištění</strong> {{pojisteni.typ_pojisteni}}</p>
  <p><strong>Částka:</strong> {{pojisteni.castka}}</p>
  <p><strong>Měsíční pojistné:</strong> {{pojisteni.mesicni_pojistne}}</p>
  <p><strong>Platnost od:</strong> {{pojisteni.platnost_od}}</p>
  <p><strong>Platnost do:</strong> {{pojisteni.platnost_do}}</p>
  {% if pojisteni.predmet_pojisteni %}
  <p><strong>Předmět pojištění:</strong> {{pojisteni.predmet_pojisteni}}</p>
  {% endif %}
  <p><strong>ID pojištění:</strong> {{pojisteni.id}}</p>

{% endblock %}

pojisteniapp/templates/pojisteniapp/pojisteni_form.html
{% extends "base_generic.html" %}

{% block content %}
{% if request.resolver_match.url_name == 'pojisteni_create' %}
<h2>Registrovat nové pojištění</h2>
{% elif request.resolver_match.url_name == 'pojisteni_update'%}
<h2>Upravit stávající pojištění</h2>
{%endif%}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Uložit" />
  </form>
{% endblock %}

pojisteniapp/templates/pojisteniapp/pojisteni_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 class= 'list-header'>Seznam sjednaných pojištění</h1>
  {% if pojisteni_list %}
  <table  class= 'list-table'>
    <thead >
      <th>Pojištěnec</th>
      <th>Typ pojištění</th>
      <th>Částka</th>
      <th>Měsíční pojistné</th>
      <th>Platnost od</th>
      <th>Platnost do</th>
      <th>ID pojištění</th>
      <th>Možné úpravy</th>
    </thead>
    {% for pojisteni in pojisteni_list %}
      <tr>
        <td class= 'td-jmeno-pojistence'>
          <a href="{{pojisteni.pojistenec.get_absolute_url}}">{{pojisteni.pojistenec.prijmeni}}, {{ pojisteni.pojistenec.jmeno }}</a>
        </td>
        <td>
          {{pojisteni.typ_pojisteni}}
        </td>
        <td>
          {{pojisteni.castka}} Kč
        </td>
        <td>
          {{pojisteni.mesicni_pojistne}} Kč
        </td>
        <td>
          {{pojisteni.platnost_od}}
        </td>
        <td>
          {{pojisteni.platnost_do}}
        </td>
        <td>
          <a href="{{pojisteni.get_absolute_url}}">{{pojisteni.id}}</a>
        </td>
        <td>
          <a class = 'button modifier' href="{% url 'pojisteni_update' pojisteni.id%}"> Upravit</a> <a class = 'button destructor' href="{% url 'pojisteni_delete' pojisteni.id%}"> Vymazat</a>
        </td>
      </tr>
    {% endfor %}
  </table>
  {% else %}
    <p>Zatím nejsou žádní pojištěnci pojištění.</p>
  {% endif %}
{% endblock %}

{% block register_entity%}
<div class= 'outside-list-button-container'>
<a class = 'button constructor' href="{% url 'pojisteni_create'%}"> Pojistit pojištěnce </a>
</div>
{% endblock %}

pojisteniapp/templates/pojisteniapp/typ-pojisteni_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Vymazat typ pojištění</h1>

<p>Jste si jistí, že chcete vymazat typ pojištění <strong>{{ typpojisteni }}</strong>?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Ano, vymazat." />
</form>

{% endblock %}

pojisteniapp/templates/pojisteniapp/typ-pojisteni_form.html
{% extends "base_generic.html" %}

{% block content %}
<h2>Registrovat nový typ pojištění</h2>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Uložit" />
  </form>
{% endblock %}

pojisteniapp/templates/pojisteniapp/typ-pojisteni_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1 class= 'list-header'>Seznam typů pojištění</h1>
  {% if typpojisteni_list %}
  <table  class= 'list-table'>
    <thead>
      <th>Typ pojištění</th>
    </thead>
    {% for typpojisteni in typpojisteni_list %}
      <tr>
        <td class = 'td-typ-pojisteni'>
          {{ typpojisteni }}
        </td>
        <td>
          <a class = 'button destructor' href="{% url 'typ-pojisteni_delete' typpojisteni.id%}"> Vymazat</a>
        </td>
      </tr>
    {% endfor %}
  </table>
  {% else %}
    <p>Zatím nejsou nabízeny žádné typy pojištění.</p>
  {% endif %}
{% endblock %}

{% block register_entity%}
<div class= 'outside-list-button-container'>
<a class = 'button constructor' href="{% url 'typ-pojisteni_create'%}"> Nový typ pojištění </a>
</div>
{% endblock %}